# Generated by Django 4.2.5 on 2023-10-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_customer',
            name='customer_phone',
        ),
    ]
